[profile.default]
src = "script"
out = "out"
libs = ["lib"]
solc = "0.8.27"
optimizer = true
optimizer_runs = 20_000
evm_version = "cancun"

fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
monad = "${RPC_URL_MONAD}"
